### ISSUE TITLE
Any plan to write a keystore encoder ?

### ISSUE THREAD

**Issue by yougg** [pavel-v-chernykh/keystore-go#1]
http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/sun/security/provider/JavaKeyStore.java?av=f#473

It's useful to replace the `keytool` command when we don't want to install JDK in the server.

**Comment by pavel-v-chernykh** [comment]
Hi, @yougg, I am on vacation now. Let's talk about it on 20 of July.

**Comment by pavel-v-chernykh** [comment]
Hi, @yougg,
Yes, it would be great to have ```keytool``` replacement but at the moment I am only interested in decoder. If you have interest in encoding part I can implement encoder as library feature without CLI part. Do you have interest?

**Comment by pavel-v-chernykh** [comment]
Hi, @yougg,
I have implemented encoder d310e13775050e63ac7b314d332b795824c0411d
You are welcome to use it.

**Comment by yougg** [comment]
:+1: 
Thanks very much.
i'll try to use it.

**Comment by pavel-v-chernykh** [comment]
@yougg You are welcome.
PS. Please, take into account that [v1.0.0](../releases/tag/v1.0.0) have been released recently with integrity check and breaking changes in the api.

**Comment by yougg** [comment]
@pavel-v-chernykh thanks for the notice, i'll pull the latest update.

**Comment by yougg** [comment]
one more question.
how to construct a valid `keystore.KeyStore` in go?
i have only `pem` encoded data now.

**Comment by pavel-v-chernykh** [comment]
Hi, @yougg

Generate private key using openssl in pem format
```shell
openssl genrsa -out privkey.pem 1024
```

Read generated pem encoded private key in go and create KeyStore.
Take into account that you can work with KeyStore like with ordinary go map.

```go
package main

import (
	"crypto/x509"
	"encoding/pem"
	"github.com/pavel-v-chernykh/keystore-go"
	"io/ioutil"
	"log"
	"os"
	"time"
)

func main() {
	pke, err := ioutil.ReadFile("./privkey.pem")
	if err != nil {
		log.Fatal(err)
	}
	p, _ := pem.Decode(pke)
	if p == nil {
		log.Fatal("Should have at least one pem block")
	}
	if p.Type != "RSA PRIVATE KEY" {
		log.Fatal("Should be a rsa private key")
	}

	keyStore := keystore.KeyStore{
		"alias": &keystore.PrivateKeyEntry{
			Entry: keystore.Entry{
				CreationDate: time.Now(),
			},
			PrivKey: p.Bytes,
		},
	}

	kfo, err := os.Create("keystore.jks")
	defer kfo.Close()

	if err != nil {
		log.Fatal(err)
	}

	err = keystore.Encode(kfo, keyStore, "password")
	if err != nil {
		log.Fatal(err)
	}

	kfi, err := os.Open("keystore.jks")
	defer kfi.Close()
	ks, err := keystore.Decode(kfi, "password")
	if err != nil {
		log.Fatal(err)
	}

	entry := ks["alias"]
	privKeyEntry := entry.(*keystore.PrivateKeyEntry)
	key, err := x509.ParsePKCS1PrivateKey(privKeyEntry.PrivKey)
	if err != nil {
		log.Fatal(err)
	}

	log.Printf("%v", key)
}
```

Hope it helps.

**Comment by pavel-v-chernykh** [comment]
Hey, @yougg does it help?

**Comment by yougg** [comment]
Hi @pavel-v-chernykh , sorry for late feedback, i was busy in past week.
Thanks for your example code, and i have an another question.

i generate a cert in go, i want to know which way shoud i put the bytes of cert into keystore?
```go
certBytes, _ := x509.CreateCertificate(......)

// 1.  use cert bytes directly
cert := keystore.Certificate{
	Type:    "CERTIFICATE",
	Content: certBytes,
}

// 2. use pem format bytes
cert := keystore.Certificate{
	Type:    "CERTIFICATE",
	Content: pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: certBytes}),
}

```

**Comment by pavel-v-chernykh** [comment]
Hi, @yougg, you are right, ```Certificate.Content``` is `X.509` `DER`-encoded certificate.
Take into account that you should specify valid ```Certificate.Type``` recognizable by `keystool`. In your case it should be "X509"
