### ISSUE TITLE
Question: Java Keytool says keystore using proprietary format 

### ISSUE THREAD

**Issue by rareddy** [pavel-v-chernykh/keystore-go#10]
So using this library I wrote a method

```
func GenerateKeyStoreFromPem(alias string, password string, permCert []byte, pemKeyKey []byte) ([]byte, error) {
	var chain []keystore.Certificate

	// decode the certificates
	for {
		blockCert, rest := pem.Decode(pemCert)
		if blockCert == nil {
			return nil, errors.New("The supplied Pem certificate could not be decoded")
		}

		chain = append(chain, keystore.Certificate{
			Type:    "X509",
			Content: blockCert.Bytes.,
		})

		// there typically more than one certificate
		if len(rest) > 0 {
			pemCert = rest
		} else {
			break
		}
	}


	blockKey, _ := pem.Decode(pemKey)
	if blockKey == nil {
		return nil, errors.New("The supplied Pem certificate key could not be decoded")
	}

	keyStore := keystore.KeyStore{
		alias: &keystore.PrivateKeyEntry{
			Entry: keystore.Entry{
				CreationDate: time.Now(),
			},
			PrivKey:   blockKey.Bytes,
			CertChain: chain,
		},
	}

	var b bytes.Buffer
	err = keystore.Encode(&b, keyStore, []byte(password))
	if err != nil {
		log.Error("Error encrypting and signing keystore. ", err)
		return nil, err
	}
	return b.Bytes(), nil
}
```

but once I write to a file, and tried to open with java keytool, then I see a warning saying 
`Warning:
The JKS keystore uses a proprietary format. It is recommended to migrate to PKCS12 which is an industry standard format using "keytool -importkeystore -srckeystore keystore.jks -destkeystore keystore.jks -deststoretype pkcs12".`

I guess I need to write the key in pcks12 format, is there any way to do that, is that not matter? I think it is `PKCS1` based.

**Comment by pavel-v-chernykh** [comment]
@rareddy hi,

This (`keystore-go`) library is an implementation of `Encoder` and `Decoder` for a proprietary Oracle (Sun) file format called `jks`. `keystore` tool from the `jdk` works with several formats: `jks`, `jceks` and `pkcs12`. `jks` was a default form till `jdk9`. From the `jdk9` default format is `pkcs12` and `jks` is deprecated. So this library is useful if you are working with legacy software that still using `jks` file format to store certificates and private keys. If you want to work with `pkcs12` file format in your golang applications you need appropriate libraries (take a look at https://pkg.go.dev/search?q=pkcs12)

References:
* JEP about switching to `pkcs12` in `jdk9` http://openjdk.java.net/jeps/229
* `KeyStore` types supported by the `keystore` tool: https://docs.oracle.com/javase/7/docs/technotes/guides/security/StandardNames.html#KeyStore
* About Keystore implementation: https://docs.oracle.com/javase/7/docs/technotes/guides/security/crypto/CryptoSpec.html#KeystoreImplementation

P.S. `pkcs1` != `jks` != `pkcs12` and so on. And to work with them you need appropriate implementations of a decoder and an encoder.

**Comment by pavel-v-chernykh** [comment]
@rareddy hi,

how are things going? do you need any more help?

**Comment by rareddy** [comment]
@pavel-v-chernykh Your suggestion was right on, I found "github.com/hetesiistvan/go-pkcs12" which does handle the pkcs12 both keystores and truststores. So, I am trying to rewrite using that. My initial tests were good. Thanks again.

**Comment by pavel-v-chernykh** [comment]
@rareddy, happy to help 😃 

Wish you good luck with your project!
