### ISSUE TITLE
Issue:  "got invalid digest"

### ISSUE THREAD

**Issue by daijuk** [pavel-v-chernykh/keystore-go#15]
One month ago, you commited decoder.go and moved `computedDigest := ksd.md.Sum(nil)` in `Decode` function to after `actualDigest, err := ksd.readBytes(uint32(ksd.md.Size()))`
The `Decode` function returns "got invalid digest" error every time after that.
The reason of error is containing digest at last of file for calculating digest.
Please re-check it.
Thank you.

**Comment by pavel-v-chernykh** [comment]
@daijuk hi, thanks for the report
