### ISSUE TITLE
Ability to decode a private key entry

### ISSUE THREAD

**Issue by Fi5t** [pavel-v-chernykh/keystore-go#18]
Does this library have the ability to decrypt a private key entry? I haven't found nor examples and docs about it.

**Comment by pavel-v-chernykh** [comment]
Take a look at this example https://github.com/pavel-v-chernykh/keystore-go/blob/master/examples/pem/main.go

**Comment by Fi5t** [comment]
That example uses only ["storepasswd"](https://docs.oracle.com/javase/8/docs/technotes/tools/unix/keytool.html#keytool_option_storepasswd) (in `keytool` terms). I want to use ["keypasswd"](https://docs.oracle.com/javase/8/docs/technotes/tools/unix/keytool.html#keytool_option_keypasswd) also. Is it possible?

**Comment by pavel-v-chernykh** [comment]
Unfortunately, this feature not supported :(

**Comment by Fi5t** [comment]
@pavel-v-chernykh thank you for the answer. It would be cool to add this feature =)

**Comment by pavel-v-chernykh** [comment]
@Fi5t I have implemented the decryption of private key entries with the custom key password. Version v3.1.0. Please, check does it work for you.

**Comment by Fi5t** [comment]
Oh, good work! API is a bit strange, but it works excellent. Thank you a lot!

**Comment by pavel-v-chernykh** [comment]
@Fi5t I'm glad to help!
Thanks for your interest in the project!
Totally agree about API. Did it that way to keep backward compatibility with v3.
Have plans to rework the API in v4.

**Comment by pavel-v-chernykh** [comment]
@Fi5t I've released [v4](https://github.com/pavel-v-chernykh/keystore-go/releases/tag/v4.0.0). The main idea behind this version to reproduce a minimal viable part of the original Java KeyStore API as close as possible. Hope you will find it more usable. Feedback is welcome.

**Comment by Fi5t** [comment]
@pavel-v-chernykh thanks! I'll review it in comming days.
