### ISSUE TITLE
getting invalid digest

### ISSUE THREAD

**Issue by janitha09** [pavel-v-chernykh/keystore-go#26]
The sampel keystore in your repository does not produce this problem 
i.e. the one here https://github.com/pavel-v-chernykh/keystore-go/blob/41c45484322d62c5a15736e40282d88ec4f37012/testdata/keystore.jks

However if I were to do this

```
keytool -genkey -alias skipper -keyalg RSA -keystore skipper.keystore -validity 30 -storetype JKS -dname "CN=localhost" -keypass skipper -storepass skipper
```
and attempt to load it like this

```
func TestKeyStoreRoundTrip(t *testing.T) {
	testCases := []struct {
		name    string
		passwod []byte
		alias   string
		outname string
	}{
		{
			`./skipper.keystore`,
			[]byte("password"),
			"skipper",
			`./skipperout.keystore`,
		},
		{
			`/home/janitha/go/src/github.com/keystore-go/testdata/keystore.jks`,
			[]byte("password"),
			"alias",
			`./samplekeystore.jks`,
		},
	}
	for i, tc := range testCases[0:] {
		t.Run(strconv.Itoa(i), func(t *testing.T) {
			fr, err := os.Open(tc.name)
			if err != nil {
				t.Fatal(err)
			}
			defer func() {
				if err := fr.Close(); err != nil {
					t.Fatal(err)
				}
			}()
			ks := keystore.New()
			pwd := tc.passwod
			if err := ks.Load(fr, pwd); err != nil {
				t.Fatal(err)
			}
		})
	}
}
```

The digests are as follows

```
computedDigest:  cd314e68e349ec8ac3a4496335b26c85ce6a97f5
actualdigest: e4059bc66cc398dcf4b2878bd9b0409949457d2e
```
The above gives `got invalid digest` from this line https://github.com/pavel-v-chernykh/keystore-go/blob/d66cbc26e181292e9725c0220796b3a682cafdcd/keystore.go#L186

```
computedDigest: 43496b66608aec887f74ca7cd6daa53887f47468
actualDigest: 43496b66608aec887f74ca7cd6daa53887f47468
```
The line below reads 20 bytes back into ksd.b which is then returned. This does not look like a sha1, but it works for your keystore sample

```
actualDigest, err := ksd.readBytes(uint32(ksd.md.Size()))
```

**Comment by pavel-v-chernykh** [comment]
@janitha09 hi,

Thanks for your interest in my project.

Looks like you have used different passwords in the line where you created keystore
```keytool -genkey -alias skipper -keyalg RSA -keystore skipper.keystore -validity 30 -storetype JKS -dname "CN=localhost" -keypass skipper -storepass skipper```

and in your test case 

```
		{
			`./skipper.keystore`,
			[]byte("password"),
			"skipper",
			`./skipperout.keystore`,
		},
```

according to the command you used for generating `skipper.keystore` the password must be `[]byte("skipper")`

I've tried your example with the password `[]byte("skipper")` and it works.

**Comment by janitha09** [comment]
Thanks for picking up on that. And thank you for creating it.
