### ISSUE TITLE
PFX format cert in TrustedCertificateEntry

### ISSUE THREAD

**Issue by tahirali-endurance** [pavel-v-chernykh/keystore-go#27]
We are trying to store **pfx** format(encoded with PKCS12 format) TrustedEntry in keystore. We are using following way:

```go
te := keystore.TrustedCertificateEntry{
		CreationTime: time.Now(),
		Certificate: keystore.Certificate{
			Content: pfxData,
			Type: "pkcs12",
		},
	}
```
Looking at test examples, it sounds like we can only pass X509 certs. Any suggestions?

**Comment by pavel-v-chernykh** [comment]
@tahirali-endurance hi,

Thanks for your interest in my project. I'll try to clarify the purpose of the library below.

JKS and PKCS#12 are just "SafeBag" containers that can be used to store encrypted private key entries and associated certificates chain or just unencrypted certificate chains (so-called trust stores). JKS and PKCS#12 signs their contents to prevent compromise. So they are just containers with very similar purposes. You just need to choose one of them (JKS or PKCS#12).

Just keep in mind that JKS is a deprecated format and this library exists just for the cases when you already have JKS files and you want/need to work with them in golang projects.

If you already have your certificates stored in PKCS#12 container use it directly using `golang.org/x/crypto/pkcs12` or `https://github.com/SSLMate/go-pkcs12` libraries. If you need to work with JKS in your application you can convert PKCS#12 into JKS yousing keytool from JDK and use my library.

`keytool -importkeystore -srckeystore <your-pkcs12-file> -srcstoretype pkcs12 -srcalias <certificate-alias-in-pkcs12>
 -destkeystore <new-jks-file> -deststoretype jks -deststorepass <store-password-for-jks> -destalias <certificate-alias-in-jks`

Hope it helps and good luck.

**Comment by tahirali-endurance** [comment]
Thanks Pavel for the clarification.
