### ISSUE TITLE
Unrecognized keystore format

### ISSUE THREAD

**Issue by soluwalana** [pavel-v-chernykh/keystore-go#29]
For some reason I am getting `Unrecognized keystore format` when using `keytool` with a keystore built with this library. 

Is this library expected to be compatible with `keytool` ?

**Comment by pavel-v-chernykh** [comment]
@soluwalana hi, please, provide an example of Go code how you use the library and keytool invocation string which fails.

**Comment by pavel-v-chernykh** [comment]
Closed due to inactivity for 10 days. If you have details, please reopen the issue.
