### ISSUE TITLE
what is the correct way to compare two keystores?

### ISSUE THREAD

**Issue by raffaelespazzoli** [pavel-v-chernykh/keystore-go#34]
Creating multiple key stores with the same content generates different binary representations, this is true even when setting the creation timestamp at the same time in each of them. I am not sure why, but perhaps is that `sha1.new()` that is time dependent.
In order to implement some sort of idempotency in my automation, I need to know if two KeyStores are equivalent. or alternatively if a set of pem-formatted certs is equivalent to a KeyStore previously created.
What is the recommended approach to solve thyis issue? 
Can a `compare` function be added to the KeyStore structure?

**Comment by raffaelespazzoli** [comment]
I ended up creating this method:
```golang
func compareKeyStore(a, b keystore.KeyStore, flog logr.Logger) bool {
	aliasesASet := strset.New(a.Aliases()...)
	aleasesBSet := strset.New(b.Aliases()...)
	if !aliasesASet.IsEqual(aleasesBSet) {
		return false
	}
	for _, alias := range a.Aliases() {
		if a.IsTrustedCertificateEntry(alias) {
			if !b.IsTrustedCertificateEntry(alias) {
				return false
			}
			TCEA, err := a.GetTrustedCertificateEntry(alias)
			if err != nil {
				flog.Error(err, "unable to get trusted cert entry for", "alias", alias)
				return false
			}
			TCEB, err := b.GetTrustedCertificateEntry(alias)
			if err != nil {
				flog.Error(err, "unable to get trusted cert entry for", "alias", alias)
				return false
			}
			if !reflect.DeepEqual(TCEA, TCEB) {
				return false
			}
		}
		if a.IsPrivateKeyEntry(alias) {
			if !b.IsPrivateKeyEntry(alias) {
				return false
			}
			PKEA, err := a.GetPrivateKeyEntry(alias, []byte{})
			if err != nil {
				flog.Error(err, "unable to get private key entry for", "alias", alias)
				return false
			}
			PKEB, err := b.GetPrivateKeyEntry(alias, []byte{})
			if err != nil {
				flog.Error(err, "unable to get private key entry for", "alias", alias)
				return false
			}
			if !reflect.DeepEqual(PKEA, PKEB) {
				return false
			}
		}
	}
	return true
}
```
maybe it can be adapted to fit in this library

**Comment by pavel-v-chernykh** [comment]
@raffaelespazzoli hi,

For `PrivateKeyEntry` a random salt is used to encrypt the content of a `PrivateKey` of the entry. Each time, you will get non-identical keystore files in a bitwise comparison.

I just implemented the option `WithCustomRandomNumberGenerator` for automation and testing. Hope it will help. Also, do not forget to use the `WithOrderedAliases` option. An example can be found at https://github.com/pavel-v-chernykh/keystore-go/blob/master/examples/compare/main.go 

`reflect.DeepEqual` can be used to compare two keystores.

Let me know whether it works or not for you.

**Comment by pavel-v-chernykh** [comment]
I've released 4.3.0 with this feature included.

**Comment by pavel-v-chernykh** [comment]
I'll try to be more clear about the options in the example https://github.com/pavel-v-chernykh/keystore-go/blob/master/examples/compare/main.go

`WithCustomRandomNumberGenerator` is required to get the same salt each time the private key is encrypted so that each time you receive an identical binary representation of the encrypted private key.
`WithOrderedAliases` is required to put entries in the same order each time the keystone is serialized so that you receive an identical binary representation for the entire keystore.

**Comment by pavel-v-chernykh** [comment]
@raffaelespazzoli hi. Did you have time to check whether it works for you?

**Comment by raffaelespazzoli** [comment]
I'm using the approach shared above for now. as long as the generated binare representation is the same, the approach would work for me.
