### ISSUE TITLE
Error with Java 18 - "got invalid magic"

### ISSUE THREAD

**Issue by pivotal-david-osullivan** [pavel-v-chernykh/keystore-go#37]
Java 18 migrates the `cacerts` keystore from JKS to a password-less PKCS12 format file. See the [release notes](https://www.oracle.com/java/technologies/javase/18all-relnotes.html) and [bug details](https://bugs.openjdk.java.net/browse/JDK-8275252).

When the `Load` method is called with the new `cacerts` file, [this error](https://github.com/pavel-v-chernykh/keystore-go/blob/7fd2f4f77866b643649fa619f43bb1ab334067e4/keystore.go#L173) is thrown.

Is it possible to add support for this new Java 18 format?

**Comment by pavel-v-chernykh** [comment]
@pivotal-david-osullivan hi,

Thanks for your interest.

This package (`keystore-go`) is intended for encoding/decoding JKS files only. It implements proprietary algorithm to do this. Unlike JKS, PKCS12 is the open format (standard) but very complex. You can find partial implementations of pkcs12 encoders/decoders in golang, e.g.
- https://github.com/golang/crypto/tree/master/pkcs12
- https://github.com/SSLMate/go-pkcs12

Unfortunately I had no success reading passwordless pkcs12 containers (like java `cacerts`) using any of them.

From my point of view it could be better to spend efforts improving existing pkcs12 library to make it work with passwordless pkcs12 container.

Here you can find my quick and dirty implementation of reading java cacerts (which is passwordless pkcs12 container) using just standard `asn1` package.

```
package main

import (
	"crypto/x509"
	"encoding/asn1"
	"log"
	"os"
)

type pfx struct {
	Version  int
	AuthSafe contentInfo
}

type contentInfo struct {
	ContentType asn1.ObjectIdentifier
	Content     asn1.RawValue `asn1:"tag:0,explicit,optional"`
}

type certBag struct {
	Id   asn1.ObjectIdentifier
	Data []byte `asn1:"tag:0,explicit"`
}

func main() {
	cacertPath := "/Library/Java/JavaVirtualMachines/amazon-corretto-18.jdk/Contents/Home/lib/security/cacerts"

	data, err := os.ReadFile(cacertPath)
	if err != nil {
		log.Fatalln(err)
	}

	var (
		pfx pfx
		rw  asn1.RawValue
		cis []contentInfo
	)

	if _, err := asn1.Unmarshal(data, &pfx); err != nil {
		log.Fatalln("pfx:", err)
	}

	if _, err := asn1.Unmarshal(pfx.AuthSafe.Content.Bytes, &rw); err != nil {
		log.Fatalln("rw:", err)
	}

	if _, err := asn1.Unmarshal(rw.Bytes, &cis); err != nil {
		log.Fatalln("cis:", err)
	}

	if _, err := asn1.Unmarshal(cis[0].Content.Bytes, &rw); err != nil {
		log.Fatalln("rw:", err)
	}

	if _, err := asn1.Unmarshal(rw.Bytes, &cis); err != nil {
		log.Fatalln("cis:", err)
	}

	for _, ci := range cis {
		var cb certBag
		if _, err := asn1.Unmarshal(ci.Content.Bytes, &cb); err != nil {
			log.Fatalln("cb:", err)
		}

		c, err := x509.ParseCertificate(cb.Data)
		if err != nil {
			log.Fatalln("x509:", err)
		}

		log.Println(c.Subject)
	}
}
```

Have a good day!

**Comment by pavel-v-chernykh** [comment]
@pivotal-david-osullivan hi, was it helpful for you?

**Comment by pivotal-david-osullivan** [comment]
Yes, thank you for the response @pavel-v-chernykh!
