### ISSUE TITLE
how to get public key

### ISSUE THREAD

**Issue by in-the-sky-a** [pavel-v-chernykh/keystore-go#38]
how to get public key, here is my example, does the public key right? 

   ks := readKeyStore("/Users/qq/merchant_keystore.jks", []byte("123456"))
    privateKeyEntey, err := ks.GetPrivateKeyEntry("merchant_key_pair", []byte("changeit"))
    assert.NoError(t, err)
    privateKeyEntry, err := x509.ParsePKCS8PrivateKey(privateKeyEntey.PrivateKey)
    privateKey :=  privateKeyEntry.(*rsa.PrivateKey)
    kkPublicKey, err := x509.ParsePKCS1PublicKey(privateKeyEntey.CertificateChain[0].Content)
    assert.NoError(t, err)
    publicKey := privateKey.PublicKey

**Comment by in-the-sky-a** [comment]
here is readKeyStore:

func readKeyStore(filename string, password []byte) keystore.KeyStore {
    f, err := os.Open(filename)
    if err != nil {
        log.Fatal(err)
    }

    defer func() {
        if err := f.Close(); err != nil {
            log.Fatal(err)
        }
    }()

    ks := keystore.New()
    if err := ks.Load(f, password); err != nil {
        log.Fatal(err) // nolint: gocritic
    }

    return ks
}

**Comment by pavel-v-chernykh** [comment]
Hello, @in-the-sky-a 

You have two options to get a public key from a valid Keystore:

1. Get the public key from the certificate located in the `CertificateChain` field of `PrivateKeyEntry`

```
	cert, err := x509.ParseCertificate(pke.CertificateChain[0].Content)
	if err != nil {
		log.Fatal(err)
	}

	log.Printf("%#v\n", cert.PublicKey.(*rsa.PublicKey))
```

2. Get the public key from the `PublicKey` field of `rsa.PrivateKey` parsed from the `PrivateKey` field of `PrivateKeyEntry`

```
	key, err := x509.ParsePKCS8PrivateKey(pke.PrivateKey)
	if err != nil {
		log.Fatal(err)
	}

	log.Printf("%#v\n", key.(*rsa.PrivateKey).PublicKey)
```

Hope it helps.

**Comment by in-the-sky-a** [comment]
@pavel-v-chernykh  got you .  thank you very much .
