### ISSUE TITLE
Question: Example for trust store?

### ISSUE THREAD

**Issue by rareddy** [pavel-v-chernykh/keystore-go#9]
Looking at https://github.com/pavel-v-chernykh/keystore-go/tree/master/examples/pem 
can you show an example for creating a truststore? if I have the `ca.crt` certificate file in pem format, is it similar to doing creating a key store but avoid ignore the private key setting?

**Comment by pavel-v-chernykh** [comment]
@rareddy hi,

you are right. In that case, a password is using to secure digest and verify Keystore integrity.

I've added `truststore` reading example. Please, have a look https://github.com/pavel-v-chernykh/keystore-go/blob/master/examples/truststore/main.go.
Usage: `go run main.go <truststore-path> <password>` for a adoptopenjdk8 installation with default password on a macOS it is a `go run main.go "/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/security/cacerts" "changeit"`

To create a `truststore` just put your certificate it in `TrustedCertificateEntry`

```
	keystore.TrustedCertificateEntry{
		Entry:       keystore.Entry{
			CreationTime: time.Now(),
		},
		Certificate: keystore.Certificate{
			Type: "X509",
			Content: certData, // your cert data   
		},
	}
```

Hope you will find it helpful.

**Comment by rareddy** [comment]
Thank you
